// <auto-generated />
using System;
using GraphQlDotNetCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQlDotNetCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQlDotNetCore.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ac048f1-9aba-47e2-a8d8-b88bdfd271c7"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("5e6455ff-12c0-4b6b-80f8-e2ff35d68151"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b8462ef1-077d-451c-8669-212e32d6fa9a"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("8a5d6e67-2802-4c7a-a337-dbd755e744bc"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1e703cc7-2847-428f-a6b6-411e93e6a649"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("8a5d6e67-2802-4c7a-a337-dbd755e744bc"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQlDotNetCore.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e6455ff-12c0-4b6b-80f8-e2ff35d68151"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("8a5d6e67-2802-4c7a-a337-dbd755e744bc"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQlDotNetCore.Account", b =>
                {
                    b.HasOne("GraphQlDotNetCore.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphQlDotNetCore.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
